travis:
  secure:
    BINSTAR_TOKEN: gYN/0QbvwKLjc1s1U7sZe4vbF4lfUUsA3wq8pWzWZCp2fbIognvoV3jtgJeT00KF/ixLzaJKTaJndasNlcRtHb39CLziMBpaOhAbWj+v0OCuAOLKNvSHx1iTPsCCG6RkKPQ/uqa4u6Occi+RRJB0WemLpHVcb46fj0twERaLwNIvPxT/p0iAa5KItcWJaNrlxo6yzMgHC9hNiVUiXqXCcoUFW+YM7OLp+pnPRRZvQHHe1hXiduW5PUPsqzmIs7IkxTarwZfdJMEvpmheho1dSyMBf+5ANVhXSv0UeIChd7GKHxmmmG8x6wTcrx5v+9iTmGPIEiSvpTvIIwcxX2avaGtqHnpBCSZ8AjNPRAU7hAnmUB0fNkJ9TyQewOHIYuh8I/7oGmG7X3notyiSW8SwpzSMUtsIw+n2aAj3gg7UMdkzteTV/Z2P8xo8uHyG0Dpdu6kZVX7As2DmcOGSaDw2o4Gfk2fMdcUGH43wVz516hsctp0MwNe7hHXeezUAbSuuYAgXPQ5+unMxVaayJP2EVozEE5aTkgoe0905SsJ539Hm0sddpeG9F8NQDICR6jDqL/bXQhkwdIViypC3Go9jdV3641yYsDyxt14JzXdM6q2xu3mxH9Hd+tkxbSQFm1b7bCqN0ZoZNzaejXWiJWq3LTHEpuIovqfINj5w3OBVAQU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
